################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

################ Swedish language ##################
[sv]
languageName = "Sv"
languageCode = "sv"
contentDir = "content/swedish"
weight = 2
