############# English navigation ##############

# main menu
[[main]]
name = "Services"
url = "/nodal_homepage/services/"
weight = 2

[[main]]
name = "Projects"
url = "/nodal_homepage/projects/"
weight = 3

[[main]]
name = "Team"
url = "/nodal_homepage/authors/"
weight = 5

[[main]]
name = "Blog"
url = "/nodal_homepage/blog/"
weight = 6


# footer menu
# (no footer links)
