############# Swedish navigation ##############

# main menu
[[main]]
name = "Tjänster"
url = "/nodal_homepage/services/"
weight = 2
[[main]]
name = "Projekt"
url = "/nodal_homepage/projects/"
weight = 3

[[main]]
name = "Team"
url = "/nodal_homepage/authors/"
weight = 5
[[main]]
name = "Blogg"
url = "/nodal_homepage/blog/"
weight = 6

# footer menu
# (no footer links)
