############# Swedish navigation ##############

# main menu
[[main]]
name = "Tjänster"
url = "services"
weight = 2
[[main]]
name = "Projekt"
url = "projects/"
weight = 3

[[main]]
name = "Team"
url = "authors"
weight = 5
[[main]]
name = "Blogg"
url = "/nodal/sv/"
weight = 6

# footer menu
# (no footer links)
