############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Projects"
url = "/projects/"
weight = 3

[[main]]
name = "Team"
url = "/authors"
weight = 4

[[main]]
name = "Blog"
url = "/blog"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1
